### ISSUE TITLE
Total payout tracking

### ISSUE THREAD

**Issue by erulabs** [ThanksApp/donate-spec#4]
A really nice feature might be to tally the total amount of donations sent to all projects (per-project tally). What’s neat about doing this is that we could highlight / discover commonly used packages that do not have a donation field (most scanned / least donated to). Alternatively, users could choose to donate to smaller / less donated packages rather than say, packages from Facebook or Airbnb, etc.

For sure the end-user feature is a v2 thing (at least), but might be worth tallying from the beginning.

**Comment by pastudan** [comment]
Definitely think we should do this, but since this this is something that is up to the implementors, so lets discuss in the Thanks repo rather than in this one. My idea behind this repo was to create a channel for discussion around the specification itself.
